name: CI:Backend tests

on:
  push:
    branches:
      - backend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm install and test
      run: |
        npm install
        npm run lint
        npm run jest
      env:
        CI: true
