name: CI:frontend
on: [push]
jobs:
  ui_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install
      run: npm install
    - uses: cypress-io/github-action@v1.16.1
      with:
        start: npm start
        spec: cypress/integration/ui_spec.js
        browser: chrome
      env:
        CI: true