name: CI:frontend:tests

on: [push]

jobs:
  ui_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install
      run: npm install
    - uses: cypress-io/github-action@v1.16.1
      with:
        start: npm start
        config-file: cypress/integration/cypress-config-dev.json
        spec: cypress/integration/ui_spec.js
        record: true
        browser: chrome
      env:
        CI: true
        CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
  integration_test:
    runs-on: ubuntu-latest
    needs: ui_test
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install
      run: npm install && npm install -g serve
    - name: build
      run: npm build
    - uses: cypress-io/github-action@v1.16.1
      with:
        start: serve -s build
        config-file: cypress/integration/cypress-config-stage.json
        spec: cypress/integration/integration_spec.js
        record: true
        browser: chrome
      env:
        CI: true
        CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_STAGING_KEY}}
        REACT_APP_RFF_WEBSOCKET: ${{secrets.REACT_APP_RFF_WEBSOCKET}}
        REACT_APP_RFF_ENDPOINT: ${{secrets.REACT_APP_RFF_ENDPOINT}}
